ProjetoFinal/config/routes.rb
Rails.application.routes.draw do
  get 'pagina_usuario/index'

  get 'sobre_pokemon_gama/index'

  get 'control_users/index'

  devise_for :users
  get 'initial_screen/index'

  resources :pokemon_trainers

  root 'initial_screen#index'

end

ProjetoFinal/app/models/pokemon_trainer.rb
class PokemonTrainer < ActiveRecord::Base

	validates_presence_of :name, :age, :sex, :city,
	:message => "não pode estar em branco."
	validates_numericality_of :age, :message => "não é um número."

end

ProjetoFinal/app/models/user.rb
class User < ActiveRecord::Base
	enum role: [:usuario_comum,:admin]

	has_one :pokemon_trainer
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ProjetoFinal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
private
	def user_not_authorized
		flash[:alert] = "Você não tem permissão para acessar esta página."
		redirect_to(request.referrer || root_path)
		
	end
 end

ProjetoFinal/app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all
  end
end

ProjetoFinal/app/controllers/initial_screen_controller.rb
class InitialScreenController < ApplicationController
  def index
  end
end

ProjetoFinal/app/controllers/pagina_usuario_controller.rb
class PaginaUsuarioController < ApplicationController
before_action :authenticate_user!


  def index
  end
end

ProjetoFinal/app/controllers/pokemon_trainers_controller.rb
class PokemonTrainersController < ApplicationController
  before_action :set_pokemon_trainer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /pokemon_trainers
  # GET /pokemon_trainers.json
  def index
    @pokemon_trainers = PokemonTrainer.all
  end

  # GET /pokemon_trainers/1
  # GET /pokemon_trainers/1.json
  def show
  end

  # GET /pokemon_trainers/new
  def new
    @pokemon_trainer = PokemonTrainer.new
  end

  # GET /pokemon_trainers/1/edit
  def edit
  end

  # POST /pokemon_trainers
  # POST /pokemon_trainers.json
  def create
    @pokemon_trainer = PokemonTrainer.new(pokemon_trainer_params)

    respond_to do |format|
      if @pokemon_trainer.save
        format.html { redirect_to @pokemon_trainer, notice: 'Treinador criado com sucesso!' }
        format.json { render :show, status: :created, location: @pokemon_trainer }
      else
        format.html { render :new }
        format.json { render json: @pokemon_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon_trainers/1
  # PATCH/PUT /pokemon_trainers/1.json
  def update
    respond_to do |format|
      if @pokemon_trainer.update(pokemon_trainer_params)
        format.html { redirect_to @pokemon_trainer, notice: 'Treinador atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @pokemon_trainer }
      else
        format.html { render :edit }
        format.json { render json: @pokemon_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon_trainers/1
  # DELETE /pokemon_trainers/1.json
  def destroy
    @pokemon_trainer.destroy
    respond_to do |format|
      format.html { redirect_to pokemon_trainers_url, notice: 'Treinador apagado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon_trainer
      @pokemon_trainer = PokemonTrainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_trainer_params
      params.require(:pokemon_trainer).permit(:name, :age, :sex, :city, :pokemon_inicial)
    end
end

ProjetoFinal/app/controllers/sobre_pokemon_gama_controller.rb
class SobrePokemonGamaController < ApplicationController
  def index
  end
end

ProjetoFinal/app/helpers/application_helper.rb
module ApplicationHelper
end

ProjetoFinal/app/helpers/control_users_helper.rb
module ControlUsersHelper
end

ProjetoFinal/app/helpers/initial_screen_helper.rb
module InitialScreenHelper
end

ProjetoFinal/app/helpers/pagina_usuario_helper.rb
module PaginaUsuarioHelper
end

ProjetoFinal/app/helpers/pokemon_trainers_helper.rb
module PokemonTrainersHelper
end

ProjetoFinal/app/helpers/sobre_pokemon_gama_helper.rb
module SobrePokemonGamaHelper
end

ProjetoFinal/app/views/control_users/index.html.erb
<div class="starter-template">
<p id="notice"><%= notice %></p>

<center><h1>Lista de Usuários</h1>
<br><br><br>
<table border="3">
  <thead>
    <tr>
      <th>Email</th>
      <%if current_user.admin?%>
      <th>Categoria</th>
      <%end%>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <%if current_user.admin?%>
        <td><%=  user.role %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div></center>

ProjetoFinal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetoFinal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Pokémon Gama</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <!-- <li class="active"><a href="#">Home</a></li> -->

            <%if user_signed_in?%>
              <%if current_user.admin?%>
                  <li><a href=<%= control_users_index_path %>>Usuários</a></li>
              <%end%>
            <li><a href=<%= pokemon_trainers_path %>>Treinadores</a></li>
            <li><a href=<%= pagina_usuario_index_path %>>Página para Usuários</a></li>
            <li><a>Usuário: <%=current_user.email%> </a></li>   
            <li><a href= <%= edit_user_registration_path %> >Editar Cadastro</a></li>
            <li><%= link_to "Sair",destroy_user_session_path, method: :delete%></li> 
            <%else%>
            <li><a>Entre no Mundo de Pokémon Gama!</a></li>
            <li><a href= <%=new_user_session_path%> >Entrar</a></li>
            <li><a href= <%=new_user_registration_path%> >Cadastrar</a></li>
            <%end%>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
	</header>

<%= yield %>

  <footer id="footer" role="contentinfo">
    <div class="container">
      <div class="row row-bottom-padded-sm">
        <div class="col-md-12">
          <p class="copyright text-center">&copy; 2016 Pacific <a href="index.html">Riot</a>. All Rights Reserved. <br> Free HTML5 Template by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> | Images by <a href="http://www.pokemon.com" target="_blank">Pokémon/Nintendo</a> &amp; <a href="https://www.youtube.com/user/AceStarThe3rd" target="_blank">AceStarThe3rd</a></p>
        </div>
      </div>
</body>
</html>

ProjetoFinal/app/views/layouts/application.html.erb.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjetoFinal" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ProjetoFinal</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

ProjetoFinal/app/views/pagina_usuario/index.html.erb
<div class="starter-template">
<p id="notice"><%= notice %></p>

<br><br><br><center><h1>Página Para Usuários</h1></br>

<br><br><br><p  class="to-animate-2"><a href="http://gspawn.com/" class="btn btn-primary btn-lg">Loja! </a>

<p class="to-animate-2"><a href= "/pokemon_trainers/new" class="btn btn-primary btn-lg">Criar Treinador</a></p>


<p class="to-animate-2"><a href="http://kids.barbie.com/pt-br" class="btn btn-primary btn-lg">Jogar no Fácil</a></p>

<p  class="to-animate-2"><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="btn btn-primary btn-lg">Cheats! </a></p></p></center>
</div>

ProjetoFinal/app/views/pokemon_trainers/_form.html.erb
<div class="starter-template">
<%= form_for(@pokemon_trainer) do |f| %>
  <% if @pokemon_trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon_trainer.errors.count, "error") %> prohibited this pokemon_trainer from being saved:</h2>

      <ul>
      <% @pokemon_trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Idade %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :Sexo %><br>
    <%= select("pokemon_trainer","sex", ['Feminino', 'Masculino'],{include_blank: "Selecione"}) %>
  </div>
  <div class="field">
    <%= f.label :Cidade %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :Pokemon_Inicial %><br>
    <%= select("pokemon_trainer","pokemon_inicial", ['Charmander', 'Bulbasaur', 'Squirtle'],{include_blank: "Selecione"})%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

ProjetoFinal/app/views/pokemon_trainers/edit.html.erb
<div class="starter-template">
<p id="notice"><%= notice %></p>
<br><br><br><br><br><center><h1>Editando Treinador Pokémon</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @pokemon_trainer %> |
<%= link_to 'Voltar', :back %>
</center>
</div>

ProjetoFinal/app/views/pokemon_trainers/index.html.erb
<div class="starter-template">
<br><br><center><p id="notice"><%= notice %></p>

<h1>Treinadores Pokémon</h1><br>
<br>
<table border =3 cellspacing =1 cellpadding ="4">
  <thead>
    <tr>
      <th><center> Nome</center></th>
      <th width="50"><center>Idade</center></th>
      <th width="80"><center>Sexo</center></th>
      <th><center>Cidade</center></th>
      <th width="80"><center>Pokémon Inicial</center></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon_trainers.each do |pokemon_trainer| %>
      <tr>
        <td><center><%= pokemon_trainer.name %></center></td>
        <td><center><%= pokemon_trainer.age %></center></td>
        <td><center><%= pokemon_trainer.sex %></center></td>
        <td><center><%= pokemon_trainer.city %></center></td>
        <td><center><%= pokemon_trainer.pokemon_inicial %></center></td>
        <%if current_user.admin?%>
        <td width="70"><center><%= link_to 'Detalhes', pokemon_trainer %></center></td>
        <td width="50"><center><%= link_to 'Editar', edit_pokemon_trainer_path(pokemon_trainer) %></center></td>
        <td width="60"><center><%= link_to 'Apagar', pokemon_trainer, method: :delete, data: { confirm: 'Confirmar ação?' } %></center></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<%= link_to 'Novo Treinador Pokémon', new_pokemon_trainer_path %>
<br><br><%= link_to 'Voltar', pagina_usuario_index_path %> </center>
</div>

ProjetoFinal/app/views/pokemon_trainers/new.html.erb
<div class="starter-template">
<br><br><br><br><br><br><center><h1>Novo Treinador Pokémon</h1>

<%= render 'form' %>

<%= link_to 'Voltar', :back %></center>
</div>

ProjetoFinal/app/views/pokemon_trainers/show.html.erb
<div class="starter-template">
<p id="notice"><%= notice %></p>
<br><br><br><br><br><br><br><br><br><br><br><center>
<p>
  <strong>Nome:</strong>
  <%= @pokemon_trainer.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @pokemon_trainer.age %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @pokemon_trainer.sex %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @pokemon_trainer.city %>
</p>

<p>
  <strong>Pokémon Inicial:</strong>
  <%= @pokemon_trainer.pokemon_inicial %>
</p>
<%= link_to 'Editar', edit_pokemon_trainer_path(@pokemon_trainer) %> |

<%= link_to 'Voltar', pokemon_trainers_path %>


</div>

ProjetoFinal/app/views/sobre_pokemon_gama/index.html.erb
      <div class="starter-template">
        <h1>O que é Pokémon Gama Version?</h1>
        <p class="lead">Os jogos de Pokémon são bem familiares ao grande público há décadas. Inúmeras pessoas, jovens ou adultos, já jogaram, ou ao menos ouviram falar, de jogos como Pokémon Yellow, ou Pokémon Ruby. Pokémon Gama não foge ao tema dos antigos jogos. Entretanto, este revolucionário jogo oferece ao jogador uma experiência completamente nova, onde "imersão" é levada a níveis nunca antes pensados. Pokémon Gama Version será o primeiro da franquia em Realidade Virtual! Nele o jogador se sentirá como um verdadeiro Treinador Pokémon, interagindo com cenários e personagens que o farão pensar que estão no mundo real, e não em um jogo. Pokémon Gama Version oferecerá um enorme ambiente Online, onde pessoas de diferentes lugares do mundo poderão interagir, trocar pokémons e batalhar. Pokémon Gama Version será um jogo revolucionário e divertirá milhares de pessoas ao redor do globo.</p>
        <p class="to-animate-2"><a href="/" class="btn btn-primary btn-lg">Página Inicial</a></p>
        <p class ="lead"><br/><br/><br/><br/>(Data de Lançamento ainda não divulgada)</p>
      </div>
</html>